cd gestureModality\bin\x86\Debug
start DiscreteGestureBasics-WPF.exe
cd ..\..\..\..
cd AppGui\AppGui\bin\Debug\
start AppGui.exe
cd ..\..\..\..
cd speechModality\speechModality\bin\Debug
start speechModality.exe
cd ..\..\..\..