/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

	/*SQUARE("[shape][SQUARE]",1500),
        TRIANGLE("[shape][TRIANGLE]",1500),
        CIRCLE("[shape][CIRCLE]",1500),*/
        
        // STATUS
        ASSISTANT_ACTIVE("[status][ASSISTANT_ACTIVE]",0),
        ASSISTANT_INACTIVE("[status][ASSISTANT_INACTIVE]",0),
        
        // SLIDE CONTROL
        NEXT_SLIDE("[action][NEXT_SLIDE]",1000),
        PREV_SLIDE("[action][PREV_SLIDE]",1000),
        CHANGE("[action][CHANGE]",1500),
        
        SUSPEND("[action][SUSPEND]",0),
        CALCULATOR("[action][CALCULATOR]",0),
        READ_SLIDE("[action][READ_SLIDE]",0),
        READ_NEXT("[action][READ_NEXT]",0),
        OPEN_HELP("[action][OPEN_HELP]",1000),
        CLOSE_HELP("[action][CLOSE_HELP]",1000),
        
        ;


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
